In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
import matplotlib.pyplot as plt

In [38]:
sequence = [
    "I like to play cricket with my friends",
    "I like to watch movies with my family",
    "I like to read books during my holidays",
    "I like to listen music every morning",
    "I like to eat pizza with my friends",
    "I like to drink coffee after my breakfast",
    "I like to learn Python during my free time",
    "I like to play football with my classmates",
    "I like to watch cricket on the weekend",
    "I like to read stories before going to sleep",
    "I like to visit beaches during my holidays",
    "I like to explore cities with my family",
    "I like to take photos during my travels",
    "I like to make videos with my friends",
    "I like to write stories during my free time",
    "I like to draw pictures in my notebook",
    "I like to sing songs with my friends",
    "I like to dance with my friends at parties",
    "I like to cook dinner with my family",
    "I like to play games after my homework",
    "I like to learn science from my teacher",
    "I like to study mathematics in my classroom",
    "I like to practice yoga every morning at home",
    "I like to ride bicycles with my friends",
    "I like to visit parks during my evening walks",
    "I like to watch cartoons with my brother",
    "I like to eat fruits after my morning exercise",
    "I like to drink juice after my lunch",
    "I like to play chess with my father",
    "I like to read novels during my vacation",
    "I like to learn languages from online classes",
    "I like to watch football with my brother",
    "I like to play badminton with my sister",
    "I like to visit museums during my city trips",
    "I like to help people in my community",
    "I like to help animals near my home",
    "I like to grow plants in my garden",
    "I like to watch series with my family",
    "I like to listen podcasts during my journey",
    "I like to write poems in my notebook",
    "I like to make drawings during my free time",
    "I like to take walks with my friends",
    "I like to eat chocolate after my dinner",
    "I like to drink water after my exercise",
    "I like to play tennis with my friends",
    "I like to watch comedy shows with my family",
    "I like to learn technology from online videos",
    "I like to visit mountains during my vacation",
    "I like to enjoy nature during my morning walks",
    "I like to practice coding during my free time",

    "The student is reading a book in class",
    "The student is writing a note in class",
    "The student is solving a problem in class",
    "The student is learning a lesson from teacher",
    "The student is answering a question in class",
    "The student is studying science in the classroom",
    "The student is studying mathematics in the classroom",
    "The student is reading a story in library",
    "The student is writing an answer in notebook",
    "The student is learning English from the teacher",
    "The student is playing cricket after the class",
    "The student is playing football after the class",
    "The student is talking with friends after school",
    "The student is walking home after the school",
    "The student is carrying books to the classroom",
    "The student is using a computer in class",
    "The student is watching a video in class",
    "The student is drawing a picture in class",
    "The student is asking a question to teacher",
    "The student is preparing notes for the exam",
    "The student is completing homework before going home",
    "The student is reading notes before the exam",
    "The student is practicing questions before the test",
    "The student is learning new words every day",
    "The student is helping friends with their homework",
    "The student is sharing books with other students",
    "The student is sitting quietly inside the classroom",
    "The student is listening carefully to the teacher",
    "The student is speaking clearly during the presentation",
    "The student is writing carefully in the notebook",
    "The student is solving difficult questions during class",
    "The student is studying regularly before the examination",
    "The student is practicing English after the class",
    "The student is practicing mathematics after the school",
    "The student is reading quietly inside the library",
    "The student is using technology during the lesson",
    "The student is watching educational videos during class",
    "The student is taking notes during the lecture",
    "The student is asking questions during the lesson",
    "The student is preparing carefully for the examination",
    "The student is working hard for the final exam",
    "The student is studying daily for the final exam",
    "The student is completing assignments before the deadline",
    "The student is discussing ideas with other students",
    "The student is learning concepts from the textbook",
    "The student is reviewing lessons before the examination",
    "The student is practicing examples from the textbook",
    "The student is reading carefully before answering questions",
    "The student is improving skills through regular practice"
]

print("Number of sentences:", len(sequence))

Number of sentences: 99


In [44]:
window_size = 3

# X = inputs/questions
# y = correct answers

X = []
y = []

for sentence in sequence:
    words = sentence.split()

    for i in range(len(words) - window_size):
        X.append(words[i:i + window_size])
        y.append(words[i + window_size])

print("First 10 input examples:")
print(X[:10])

print("First 10 answers:")
print(y[:10])

First 10 input examples:
[['I', 'like', 'to'], ['like', 'to', 'play'], ['to', 'play', 'cricket'], ['play', 'cricket', 'with'], ['cricket', 'with', 'my'], ['I', 'like', 'to'], ['like', 'to', 'watch'], ['to', 'watch', 'movies'], ['watch', 'movies', 'with'], ['movies', 'with', 'my']]
First 10 answers:
['play', 'cricket', 'with', 'my', 'friends', 'watch', 'movies', 'with', 'my', 'family']


In [46]:
# Create a list of all unique words
vocabulary = sorted(set(
    word
    for sentence in sequence
    for word in sentence.split()
))

# Give each word a number
word_to_int = {
    word: i for i, word in enumerate(vocabulary)
}

print("Vocabulary size:", len(vocabulary))
print("Word to number:")
print(word_to_int)

Vocabulary size: 196
Word to number:
{'English': 0, 'I': 1, 'Python': 2, 'The': 3, 'a': 4, 'after': 5, 'an': 6, 'animals': 7, 'answer': 8, 'answering': 9, 'asking': 10, 'assignments': 11, 'at': 12, 'badminton': 13, 'beaches': 14, 'before': 15, 'bicycles': 16, 'book': 17, 'books': 18, 'breakfast': 19, 'brother': 20, 'carefully': 21, 'carrying': 22, 'cartoons': 23, 'chess': 24, 'chocolate': 25, 'cities': 26, 'city': 27, 'class': 28, 'classes': 29, 'classmates': 30, 'classroom': 31, 'clearly': 32, 'coding': 33, 'coffee': 34, 'comedy': 35, 'community': 36, 'completing': 37, 'computer': 38, 'concepts': 39, 'cook': 40, 'cricket': 41, 'daily': 42, 'dance': 43, 'day': 44, 'deadline': 45, 'difficult': 46, 'dinner': 47, 'discussing': 48, 'draw': 49, 'drawing': 50, 'drawings': 51, 'drink': 52, 'during': 53, 'eat': 54, 'educational': 55, 'enjoy': 56, 'evening': 57, 'every': 58, 'exam': 59, 'examination': 60, 'examples': 61, 'exercise': 62, 'explore': 63, 'family': 64, 'father': 65, 'final': 66, 'f

In [47]:
X_numeric = []
y_numeric = []

for inputs, answer in zip(X, y):
    X_numeric.append([word_to_int[word] for word in inputs])
    y_numeric.append(word_to_int[answer])

X_numeric = np.array(X_numeric)
y_numeric = np.array(y_numeric)

print("X numeric:")
print(X_numeric[:10])

print("y numeric:")
print(y_numeric[:10])

X numeric:
[[  1  97 176]
 [ 97 176 127]
 [176 127  41]
 [127  41 190]
 [ 41 190 108]
 [  1  97 176]
 [ 97 176 186]
 [176 186 105]
 [186 105 190]
 [105 190 108]]
y numeric:
[127  41 190 108  70 186 105 190 108  64]


In [48]:
X_numeric = X_numeric.reshape(
    (X_numeric.shape[0], X_numeric.shape[1], 1)
)

print("New X shape:", X_numeric.shape)

New X shape: (508, 3, 1)


In [49]:
model = Sequential()

model.add(
    SimpleRNN(
        50,
        activation='relu',
        input_shape=(window_size, 1)
    )
)

model.add(Dense(len(vocabulary), activation='softmax'))

print("Model created successfully!")

Model created successfully!


In [50]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy'
)

model.fit(
    X_numeric,
    y_numeric,
    epochs=500,
    verbose=0
)

print("Training complete.")

Training complete.


In [51]:
test_input = ["I", "like","playing"]

# Convert words to numbers
test_numeric = np.array([
    word_to_int[word] for word in test_input
])

# RNN expects: samples, timesteps, features
test_numeric = test_numeric.reshape((1, window_size, 1))

# Predict
predicted = model.predict(test_numeric, verbose=0)

# Get the word with the highest probability
predicted_index = np.argmax(predicted)

# Convert number back to word
predicted_word = vocabulary[predicted_index]

print("Input words:", test_input)
print("Predicted next word:", predicted_word)

test_input = ["The", "student","is"]

# Convert words to numbers
test_numeric = np.array([
    word_to_int[word] for word in test_input
])

# RNN expects: samples, timesteps, features
test_numeric = test_numeric.reshape((1, window_size, 1))

# Predict
predicted = model.predict(test_numeric, verbose=0)

# Get the word with the highest probability
predicted_index = np.argmax(predicted)

# Convert number back to word
predicted_word = vocabulary[predicted_index]

print("Input words:", test_input)
print("Predicted next word:", predicted_word)

Input words: ['I', 'like', 'playing']
Predicted next word: learn
Input words: ['The', 'student', 'is']
Predicted next word: studying


In [52]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense


sentence = "I love to play cricket"


words = sentence.split()


vocabulary = sorted(set(words))

word_to_int = {word: i for i, word in enumerate(vocabulary)}
int_to_word = {i: word for word, i in word_to_int.items()}


window_size = 3
X = []
y = []

for i in range(len(words) - window_size):
    X.append([
        word_to_int[words[i + 1]],
        word_to_int[words[i + 2]],
        word_to_int[words[i + 3]]
    ])

    y.append(word_to_int[words[i]])


X = np.array(X)
y = np.array(y)

print("X:", X)
print("y:", y)

X = X.reshape((X.shape[0], X.shape[1], 1))

print("New X shape:", X.shape)

model = Sequential()

model.add(
    SimpleRNN(
        50,
        activation='relu',
        input_shape=(window_size, 1)
    )
)

model.add(Dense(len(vocabulary), activation='softmax'))


model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy'
)


model.fit(X, y, epochs=500, verbose=0)

print("Training complete.")


test_input = ["to", "play", "cricket"]

test_numeric = np.array([
    word_to_int[word] for word in test_input
])

test_numeric = test_numeric.reshape((1, window_size, 1))

predicted = model.predict(test_numeric, verbose=0)

predicted_index = np.argmax(predicted)

predicted_word = int_to_word[predicted_index]

print("Input:", test_input)
print("Predicted previous word:", predicted_word)

X: [[2 4 3]
 [4 3 1]]
y: [0 2]
New X shape: (2, 3, 1)
Training complete.
Input: ['to', 'play', 'cricket']
Predicted previous word: love
